# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgis
  encoding: unicode
  pool: 5
  username: <%= ENV['LOCAL_PG_USER'] %>
  host: <%= ENV['LOCAL_HOST'] %>
  password:
  min_messages: warning
  schema_search_path: "public,postgis"

development:
  <<: *default
  database: geolocationapp_development
  script_dir: /usr/local/share/postgis
  username: geo_rails_test
  password:
  su_username: <%= ENV['GEO_SUPERUSER'] %>
  su_password: <%= ENV['GEO_SUPER_PWD'] %>
  username: <%= ENV['GEO_USER'] %>
  password: <%= ENV['GEO_PWD'] %>

test:
  <<: *default
  database: geolocationapp_test
  script_dir: /usr/local/share/postgis
  su_username: <%= ENV['GEO_SUPERUSER'] %>
  su_password: <%= ENV['GEO_SUPER_PWD'] %>
  username: <%= ENV['GEO_USER'] %>
  password: <%= ENV['GEO_PWD'] %>

production:
  <<: *default
  database: geolocationapp_production
